CREATE TABLE USER (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL ,
    PASSWORD VARCHAR(255) NOT NULL ,
    EMAIL VARCHAR(50) NOT NULL ,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED ENUM('TRUE','FALSE') DEFAULT 'FALSE',
    ROLE ENUM('ADMIN', 'USER') DEFAULT 'USER'
);

CREATE TABLE NOTIFICATION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL ,
    CONTENT VARCHAR(2000) NOT NULL ,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED ENUM('TRUE','FALSE') DEFAULT 'FALSE',
    HITS INT NOT NULL DEFAULT 0
);